language: node_js
node_js:
  - "5"
  - "4"

before_script:
  # Set a display port and start xvfb so firefox has an x server to render into
  # while testing. Without this Firefox will try to launch but would fail.
  # Firefox is a fallback for untrusted pulls that won't have access to
  # browserstack.
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - npm install -g grunt-cli

script: npm run deploy

env:
  global:
  - ENCRYPTION_LABEL: "b410a1096d5b"
  - COMMIT_AUTHOR_EMAIL: "mzgoddard@gmail.com"

addons:
  firefox: "latest"
