init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - nodejs_version: 5
    - nodejs_version: 4

matrix:
  allow_failures:
    - nodejs_version: 4

cache:
  - "%APPDATA%\\npm-cache" # npm cache

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - npm install
  - npm install -g grunt-cli


build: off

test_script:
  - node --version
  - npm --version
  - cmd: npm test
